"""add document tables

Revision ID: 23c97cd68eba
Revises: aa2539f28213
Create Date: 2026-09-28 18:31:24.506385

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c97cd68eba'
down_revision: Union[str, Sequence[str], None] = 'aa2539f28213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tables',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('markdown', sa.String(), nullable=False),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_html_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'table_index')
    )
    op.create_index(op.f('ix_document_tables_document_id'), 'document_tables', ['document_id'], unique=False)
    # ### end Alembic commands ###

    # Same access as the other corpus tables: readable by any signed-in user, written only
    # by ingestion over the direct connection (which bypasses RLS).
    op.execute("alter table document_tables enable row level security")
    op.execute(
        "create policy document_tables_select_authenticated on document_tables"
        " for select to authenticated using (true)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_tables_document_id'), table_name='document_tables')
    op.drop_table('document_tables')
    # ### end Alembic commands ###
