"""initial schema

Revision ID: aa2539f28213
Revises: 
Create Date: 2026-09-28 16:57:37.449992

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2539f28213'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    "users",
    "source_documents",
    "document_chunks",
    "chat_threads",
    "chat_messages",
    "message_citations",
)

OWNS_THREAD = "exists (select 1 from chat_threads t where t.id = {thread_id} and t.user_id = auth.uid())"
OWNS_MESSAGE = (
    "exists (select 1 from chat_messages m join chat_threads t on t.id = m.thread_id"
    " where m.id = message_citations.message_id and t.user_id = auth.uid())"
)

# The backend's direct Postgres connection bypasses RLS; these policies protect the
# tables when accessed through Supabase's API with a user JWT. Anything without a
# policy (e.g. writes to documents) is denied for anon/authenticated roles.
POLICIES = (
    ("users", "users_select_own", "select", "auth.uid() = id", None),
    ("users", "users_update_own", "update", "auth.uid() = id", "auth.uid() = id"),
    ("source_documents", "source_documents_select_authenticated", "select", "true", None),
    ("document_chunks", "document_chunks_select_authenticated", "select", "true", None),
    ("chat_threads", "chat_threads_select_own", "select", "auth.uid() = user_id", None),
    ("chat_threads", "chat_threads_insert_own", "insert", None, "auth.uid() = user_id"),
    ("chat_threads", "chat_threads_update_own", "update", "auth.uid() = user_id", "auth.uid() = user_id"),
    ("chat_threads", "chat_threads_delete_own", "delete", "auth.uid() = user_id", None),
    ("chat_messages", "chat_messages_select_own", "select", OWNS_THREAD.format(thread_id="chat_messages.thread_id"), None),
    ("chat_messages", "chat_messages_insert_own", "insert", None, OWNS_THREAD.format(thread_id="chat_messages.thread_id")),
    ("message_citations", "message_citations_select_own", "select", OWNS_MESSAGE, None),
    ("message_citations", "message_citations_insert_own", "insert", None, OWNS_MESSAGE),
)


def create_rls_policies() -> None:
    for table in TABLES:
        op.execute(f"alter table {table} enable row level security")

    for table, name, command, using, check in POLICIES:
        sql = f"create policy {name} on {table} for {command} to authenticated"
        if using:
            sql += f" using ({using})"
        if check:
            sql += f" with check ({check})"
        op.execute(sql)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create extension if not exists vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('filing_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('primary_document', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('ix_source_documents_ticker_fiscal_year', 'source_documents', ['ticker', 'fiscal_year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_threads',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), server_default='New chat', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_search_vector_gin', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant', 'system')", name='role_valid'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'sequence')
    )
    op.create_table('message_citations',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('filing_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'citation_index')
    )
    op.create_index(op.f('ix_message_citations_chunk_id'), 'message_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    # ### end Alembic commands ###

    create_rls_policies()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_chunk_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_table('chat_messages')
    op.drop_index('ix_document_chunks_search_vector_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_table('users')
    op.drop_index('ix_source_documents_ticker_fiscal_year', table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###

    # Policies are dropped together with their tables.
    op.execute("drop extension if exists vector")
